name: mwg
services:
  mwg2:
    container_name: mwg2
    build:
      context: .
    volumes:
      - ./wg0.conf:/mwg/wg0.conf:ro
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    devices:
      - /dev/net/tun:/dev/net/tun
    sysctls:
      - net.ipv4.ip_forward=1
    ports:
      - 51830:51830/udp
    networks:
      mynet:
        ipv4_address: 172.22.0.14
    tty: true
    restart: always

networks:
  mynet:
    name: mynet
    driver: bridge
    ipam:
      config:
      - subnet: 172.22.0.0/24
        gateway: 172.22.0.1