# mwg2 - vmpico
[Interface]
PrivateKey = 
Address = 10.13.14.2/24
ListenPort = 51830
PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE

# mwg3 - mikrotik1
[Peer]
PublicKey = 
AllowedIPs = 10.13.14.3/32, 10.13.14.0/24
PersistentKeepalive = 25

# mwg1 - ruvds
[Peer]
PublicKey = 
AllowedIPs = 10.13.14.1/32, 10.13.14.0/24
PersistentKeepalive = 25
