# mwg2 - vmpico
[Interface]
PrivateKey = 
Address = 10.13.14.2/24
ListenPort = 51830
# PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
# PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE

PostUp = iptables -I FORWARD 1 -i %i -o eth0 -s 10.13.14.3/32 -j ACCEPT
PostUp = iptables -I FORWARD 2 -i eth0 -o %i -d 10.13.14.3/32 -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
PostUp = iptables -t nat -I POSTROUTING 1 -s 10.13.14.3/32 -o eth0 -j MASQUERADE
PostUp = iptables -I FORWARD 3 -i %i -o eth0 -s 172.24.0.0/24 -d 172.22.0.0/24 -j ACCEPT
PostUp = iptables -I FORWARD 4 -i eth0 -o %i -s 172.22.0.0/24 -d 172.24.0.0/24 -j ACCEPT

PostDown = iptables -D FORWARD -i %i -o eth0 -s 10.13.14.3/32 -j ACCEPT 2>/dev/null || true
PostDown = iptables -D FORWARD -i eth0 -o %i -d 10.13.14.3/32 -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT 2>/dev/null || true
PostDown = iptables -t nat -D POSTROUTING -s 10.13.14.3/32 -o eth0 -j MASQUERADE 2>/dev/null || true
PostDown = iptables -D FORWARD -i %i -o eth0 -s 172.24.0.0/24 -d 172.22.0.0/24 -j ACCEPT 2>/dev/null || true
PostDown = iptables -D FORWARD -i eth0 -o %i -s 172.22.0.0/24 -d 172.24.0.0/24 -j ACCEPT 2>/dev/null || true

# mwg1 - ruvds
[Peer]
PublicKey = 
AllowedIPs = 10.13.14.1/32, 10.13.14.3/32, 172.24.0.0/24
Endpoint = 194.87.57.67:51830
PersistentKeepalive = 25
