# mikrotik
[Interface]
PrivateKey = 
Address = 10.13.14.2/24

# vmpico
[Peer]
PublicKey = C/TElZazrrKlPcuxiu3prQ7OFTyhwcbe+qTvqoZxpEU=
AllowedIPs = 10.13.14.1/32
Endpoint = 103.7.54.224:51830
PersistentKeepalive = 25