name: mwg
services:
  mwg1_srv:
    container_name: mwg1
    build:
      context: .
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    networks:
      mynet:
        ipv4_address: 172.21.0.14
    ports:
      - 51830:51830/udp
    tty: true
    restart: always

networks:
  mynet:
    name: mynet
    external: true