# vmpico
[Interface]
PrivateKey = +L07r6L3ufBBnRPJFvprMrPBAvFlSWAGwdtdkp+LN24=
Address = 10.13.14.1/24
ListenPort = 51830
PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE

# mikrotik1
[Peer]
PublicKey = HNeJMvvHxrY86KoCzD7LeUCqTia1kAJsi1GBHpWTKDc=
AllowedIPs = 10.13.14.2/32
PersistentKeepalive = 25
