# mwg1 - ruvds
[Interface]
PrivateKey = 
Address = 10.13.14.1/24
ListenPort = 51830
PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE

# mwg2 - vmpico
[Peer]
PublicKey = 
AllowedIPs = 10.13.14.2/32, 172.22.0.0/24
Endpoint = 103.7.54.224:51830
PersistentKeepalive = 25

# mwg3 - mikrotik1
[Peer]
PublicKey = 
AllowedIPs = 10.13.14.3/32
PersistentKeepalive = 25
